name: Terraform Static Code Analysis

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'

    # Login to Azure using federated credentials
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        federated-credential: 'azure-federated-credentials'

    # Terraform Format Check
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: infrastructure

    # Terraform Validation
    - name: Terraform Validate
      run: terraform validate
      working-directory: infrastructure

    # Run tfsec
    - name: Run tfsec
      uses: triat/terraform-security-scan@v3
      with:
        tfsec_actions_working_dir: infrastructure  # Specify the directory where your Terraform files are located
        tfsec_version: 'latest'  # Optionally, specify a version of tfsec to use
