name: Terraform Lint and Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Login to Azure using federated credentials
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        federated-credential: 'azure-federated-credentials'

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'

    # Install tflint for linting Terraform files
    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      working-directory: infrastructure  # Ensure this is the correct path where your Terraform files are located

    # Run tflint to lint Terraform files
    - name: Terraform Lint
      run: tflint
      working-directory: infrastructure  # Consistent use of the correct directory

    # Terraform Plan to create an execution plan
    - name: Terraform Plan
      run: terraform plan
      working-directory: infrastructure  # Consistent use of the correct directory
