name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infrastructure  # specify the directory containing the Terraform files
