name: Terraform Lint and Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'

    # Install tflint
    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      working-directory: infrastructure  # Ensure this is the correct path where your Terraform files are located

    # Run tflint
    - name: Terraform Lint
      run: tflint
      working-directory: infrastructure  # Consistent use of the correct directory

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan
      working-directory: infrastructure  # Consistent use of the correct directory
