name: Terraform Lint and Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'
    - name: Terraform Lint
      run: tflint
    - name: Terraform Plan
      run: terraform plan
