name: Terraform Static Code Analysis

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.1.0'

    # Terraform Format Check
    - name: Terraform Format
      run: terraform fmt -check

    # Terraform Validation
    - name: Terraform Validate
      run: terraform validate

    # Run tfsec
    - name: Run tfsec
      uses: triat/terraform-security-scan@v3
      with:
        tfsec_actions_working_dir: '.' # Ensure tfsec runs in the root directory containing Terraform files
        tfsec_version: 'latest' # Optionally, specify a version of tfsec to use
